/*
 * This file is autogenerated with bcop:
 * The Ecomp option code generator
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 */

#ifndef _SCALEADDON_OPTIONS_H
#define _SCALEADDON_OPTIONS_H

#ifndef _SCALEADDON_OPTIONS_INTERNAL
#define getCompPluginInfo scaleaddonOptionsGetCompPluginInfo
#endif

#ifdef  __cplusplus
extern "C" {
#endif

CompPluginVTable *scaleaddonOptionsGetCompPluginInfo (void);

typedef enum
{
    ScaleaddonDisplayOptionClose,
    ScaleaddonDisplayOptionZoom,
    ScaleaddonDisplayOptionNum
} ScaleaddonDisplayOptions;

typedef void (*scaleaddonDisplayOptionChangeNotifyProc) (CompDisplay *display, CompOption *opt, ScaleaddonDisplayOptions num);

CompOption *scaleaddonGetDisplayOption (CompDisplay *d, ScaleaddonDisplayOptions num);

typedef enum
{
    ScaleaddonScreenOptionWindowTitle,
    ScaleaddonScreenOptionTitleBold,
    ScaleaddonScreenOptionTitleSize,
    ScaleaddonScreenOptionBorderSize,
    ScaleaddonScreenOptionFontColor,
    ScaleaddonScreenOptionBackColor,
    ScaleaddonScreenOptionWindowHighlight,
    ScaleaddonScreenOptionHighlightColor,
    ScaleaddonScreenOptionLayoutMode,
    ScaleaddonScreenOptionNum
} ScaleaddonScreenOptions;

typedef void (*scaleaddonScreenOptionChangeNotifyProc) (CompScreen *screen, CompOption *opt, ScaleaddonScreenOptions num);

CompOption *scaleaddonGetScreenOption (CompScreen *s, ScaleaddonScreenOptions num);

typedef enum
{
    LayoutModeNormal = 0,
    LayoutModeOrganicExperimental = 1,
} ScaleaddonLayoutModeEnum;

CompAction *     scaleaddonGetClose (CompDisplay *d);
void             scaleaddonSetCloseInitiate (CompDisplay *d, CompActionCallBackProc init);
void             scaleaddonSetCloseTerminate (CompDisplay *d, CompActionCallBackProc term);
CompOption *     scaleaddonGetCloseOption (CompDisplay *d);
void             scaleaddonSetCloseNotify (CompDisplay *d, scaleaddonDisplayOptionChangeNotifyProc notify);
            
CompAction *     scaleaddonGetZoom (CompDisplay *d);
void             scaleaddonSetZoomInitiate (CompDisplay *d, CompActionCallBackProc init);
void             scaleaddonSetZoomTerminate (CompDisplay *d, CompActionCallBackProc term);
CompOption *     scaleaddonGetZoomOption (CompDisplay *d);
void             scaleaddonSetZoomNotify (CompDisplay *d, scaleaddonDisplayOptionChangeNotifyProc notify);
            
Bool             scaleaddonGetWindowTitle (CompScreen *s);
CompOption *     scaleaddonGetWindowTitleOption (CompScreen *s);
void             scaleaddonSetWindowTitleNotify (CompScreen *s, scaleaddonScreenOptionChangeNotifyProc notify);
            
Bool             scaleaddonGetTitleBold (CompScreen *s);
CompOption *     scaleaddonGetTitleBoldOption (CompScreen *s);
void             scaleaddonSetTitleBoldNotify (CompScreen *s, scaleaddonScreenOptionChangeNotifyProc notify);
            
int              scaleaddonGetTitleSize (CompScreen *s);
CompOption *     scaleaddonGetTitleSizeOption (CompScreen *s);
void             scaleaddonSetTitleSizeNotify (CompScreen *s, scaleaddonScreenOptionChangeNotifyProc notify);
            
int              scaleaddonGetBorderSize (CompScreen *s);
CompOption *     scaleaddonGetBorderSizeOption (CompScreen *s);
void             scaleaddonSetBorderSizeNotify (CompScreen *s, scaleaddonScreenOptionChangeNotifyProc notify);
            
unsigned short * scaleaddonGetFontColor (CompScreen *s);
unsigned short   scaleaddonGetFontColorRed (CompScreen *s);
unsigned short   scaleaddonGetFontColorGreen (CompScreen *s);
unsigned short   scaleaddonGetFontColorBlue (CompScreen *s);
unsigned short   scaleaddonGetFontColorAlpha (CompScreen *s);
CompOption *     scaleaddonGetFontColorOption (CompScreen *s);
void             scaleaddonSetFontColorNotify (CompScreen *s, scaleaddonScreenOptionChangeNotifyProc notify);
            
unsigned short * scaleaddonGetBackColor (CompScreen *s);
unsigned short   scaleaddonGetBackColorRed (CompScreen *s);
unsigned short   scaleaddonGetBackColorGreen (CompScreen *s);
unsigned short   scaleaddonGetBackColorBlue (CompScreen *s);
unsigned short   scaleaddonGetBackColorAlpha (CompScreen *s);
CompOption *     scaleaddonGetBackColorOption (CompScreen *s);
void             scaleaddonSetBackColorNotify (CompScreen *s, scaleaddonScreenOptionChangeNotifyProc notify);
            
Bool             scaleaddonGetWindowHighlight (CompScreen *s);
CompOption *     scaleaddonGetWindowHighlightOption (CompScreen *s);
void             scaleaddonSetWindowHighlightNotify (CompScreen *s, scaleaddonScreenOptionChangeNotifyProc notify);
            
unsigned short * scaleaddonGetHighlightColor (CompScreen *s);
unsigned short   scaleaddonGetHighlightColorRed (CompScreen *s);
unsigned short   scaleaddonGetHighlightColorGreen (CompScreen *s);
unsigned short   scaleaddonGetHighlightColorBlue (CompScreen *s);
unsigned short   scaleaddonGetHighlightColorAlpha (CompScreen *s);
CompOption *     scaleaddonGetHighlightColorOption (CompScreen *s);
void             scaleaddonSetHighlightColorNotify (CompScreen *s, scaleaddonScreenOptionChangeNotifyProc notify);
            
int              scaleaddonGetLayoutMode (CompScreen *s);
CompOption *     scaleaddonGetLayoutModeOption (CompScreen *s);
void             scaleaddonSetLayoutModeNotify (CompScreen *s, scaleaddonScreenOptionChangeNotifyProc notify);
            
#ifdef  __cplusplus
}
#endif

#endif
