/*
 * This file is autogenerated with bcop:
 * The Ecomp option code generator
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 */

#ifndef _MBLUR_OPTIONS_H
#define _MBLUR_OPTIONS_H

#ifndef _MBLUR_OPTIONS_INTERNAL
#define getCompPluginInfo mblurOptionsGetCompPluginInfo
#endif

#ifdef  __cplusplus
extern "C" {
#endif

CompPluginVTable *mblurOptionsGetCompPluginInfo (void);

typedef enum
{
    MblurDisplayOptionInitiate,
    MblurDisplayOptionNum
} MblurDisplayOptions;

typedef void (*mblurDisplayOptionChangeNotifyProc) (CompDisplay *display, CompOption *opt, MblurDisplayOptions num);

CompOption *mblurGetDisplayOption (CompDisplay *d, MblurDisplayOptions num);

typedef enum
{
    MblurScreenOptionMode,
    MblurScreenOptionStrength,
    MblurScreenOptionOnTransformedScreen,
    MblurScreenOptionNum
} MblurScreenOptions;

typedef void (*mblurScreenOptionChangeNotifyProc) (CompScreen *screen, CompOption *opt, MblurScreenOptions num);

CompOption *mblurGetScreenOption (CompScreen *s, MblurScreenOptions num);

typedef enum
{
    ModeTextureCopy = 0,
    ModeAccumulationBuffer = 1,
} MblurModeEnum;

CompAction *     mblurGetInitiate (CompDisplay *d);
void             mblurSetInitiateInitiate (CompDisplay *d, CompActionCallBackProc init);
void             mblurSetInitiateTerminate (CompDisplay *d, CompActionCallBackProc term);
CompOption *     mblurGetInitiateOption (CompDisplay *d);
void             mblurSetInitiateNotify (CompDisplay *d, mblurDisplayOptionChangeNotifyProc notify);
            
int              mblurGetMode (CompScreen *s);
CompOption *     mblurGetModeOption (CompScreen *s);
void             mblurSetModeNotify (CompScreen *s, mblurScreenOptionChangeNotifyProc notify);
            
float            mblurGetStrength (CompScreen *s);
CompOption *     mblurGetStrengthOption (CompScreen *s);
void             mblurSetStrengthNotify (CompScreen *s, mblurScreenOptionChangeNotifyProc notify);
            
Bool             mblurGetOnTransformedScreen (CompScreen *s);
CompOption *     mblurGetOnTransformedScreenOption (CompScreen *s);
void             mblurSetOnTransformedScreenNotify (CompScreen *s, mblurScreenOptionChangeNotifyProc notify);
            
#ifdef  __cplusplus
}
#endif

#endif
