/*
 * This file is autogenerated with bcop:
 * The Ecomp option code generator
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 */

#ifndef _WALL_OPTIONS_H
#define _WALL_OPTIONS_H

#ifndef _WALL_OPTIONS_INTERNAL
#define getCompPluginInfo wallOptionsGetCompPluginInfo
#endif

#ifdef  __cplusplus
extern "C" {
#endif

CompPluginVTable *wallOptionsGetCompPluginInfo (void);

typedef enum
{
    WallDisplayOptionShowSwitcher,
    WallDisplayOptionMiniscreen,
    WallDisplayOptionPreviewTimeout,
    WallDisplayOptionEdgeRadius,
    WallDisplayOptionOutlineColor,
    WallDisplayOptionBackgroundGradientBaseColor,
    WallDisplayOptionBackgroundGradientHighlightColor,
    WallDisplayOptionBackgroundGradientShadowColor,
    WallDisplayOptionThumbGradientBaseColor,
    WallDisplayOptionThumbGradientHighlightColor,
    WallDisplayOptionThumbHighlightGradientBaseColor,
    WallDisplayOptionThumbHighlightGradientShadowColor,
    WallDisplayOptionArrowBaseColor,
    WallDisplayOptionArrowShadowColor,
    WallDisplayOptionAllowWraparound,
    WallDisplayOptionSlideDuration,
    WallDisplayOptionLeft,
    WallDisplayOptionRight,
    WallDisplayOptionUp,
    WallDisplayOptionDown,
    WallDisplayOptionNext,
    WallDisplayOptionPrev,
    WallDisplayOptionLeftWindow,
    WallDisplayOptionRightWindow,
    WallDisplayOptionUpWindow,
    WallDisplayOptionDownWindow,
    WallDisplayOptionFlipLeft,
    WallDisplayOptionFlipRight,
    WallDisplayOptionFlipUp,
    WallDisplayOptionFlipDown,
    WallDisplayOptionNum
} WallDisplayOptions;

typedef void (*wallDisplayOptionChangeNotifyProc) (CompDisplay *display, CompOption *opt, WallDisplayOptions num);

CompOption *wallGetDisplayOption (CompDisplay *d, WallDisplayOptions num);

typedef enum
{
    WallScreenOptionMmmode,
    WallScreenOptionEdgeflipPointer,
    WallScreenOptionEdgeflipMove,
    WallScreenOptionEdgeflipDnd,
    WallScreenOptionNum
} WallScreenOptions;

typedef void (*wallScreenOptionChangeNotifyProc) (CompScreen *screen, CompOption *opt, WallScreenOptions num);

CompOption *wallGetScreenOption (CompScreen *s, WallScreenOptions num);

typedef enum
{
    MmmodeSwitchAll = 0,
    MmmodeSwitchSeparately = 1,
} WallMmmodeEnum;

Bool             wallGetShowSwitcher (CompDisplay *d);
CompOption *     wallGetShowSwitcherOption (CompDisplay *d);
void             wallSetShowSwitcherNotify (CompDisplay *d, wallDisplayOptionChangeNotifyProc notify);
            
Bool             wallGetMiniscreen (CompDisplay *d);
CompOption *     wallGetMiniscreenOption (CompDisplay *d);
void             wallSetMiniscreenNotify (CompDisplay *d, wallDisplayOptionChangeNotifyProc notify);
            
float            wallGetPreviewTimeout (CompDisplay *d);
CompOption *     wallGetPreviewTimeoutOption (CompDisplay *d);
void             wallSetPreviewTimeoutNotify (CompDisplay *d, wallDisplayOptionChangeNotifyProc notify);
            
int              wallGetEdgeRadius (CompDisplay *d);
CompOption *     wallGetEdgeRadiusOption (CompDisplay *d);
void             wallSetEdgeRadiusNotify (CompDisplay *d, wallDisplayOptionChangeNotifyProc notify);
            
unsigned short * wallGetOutlineColor (CompDisplay *d);
unsigned short   wallGetOutlineColorRed (CompDisplay *d);
unsigned short   wallGetOutlineColorGreen (CompDisplay *d);
unsigned short   wallGetOutlineColorBlue (CompDisplay *d);
unsigned short   wallGetOutlineColorAlpha (CompDisplay *d);
CompOption *     wallGetOutlineColorOption (CompDisplay *d);
void             wallSetOutlineColorNotify (CompDisplay *d, wallDisplayOptionChangeNotifyProc notify);
            
unsigned short * wallGetBackgroundGradientBaseColor (CompDisplay *d);
unsigned short   wallGetBackgroundGradientBaseColorRed (CompDisplay *d);
unsigned short   wallGetBackgroundGradientBaseColorGreen (CompDisplay *d);
unsigned short   wallGetBackgroundGradientBaseColorBlue (CompDisplay *d);
unsigned short   wallGetBackgroundGradientBaseColorAlpha (CompDisplay *d);
CompOption *     wallGetBackgroundGradientBaseColorOption (CompDisplay *d);
void             wallSetBackgroundGradientBaseColorNotify (CompDisplay *d, wallDisplayOptionChangeNotifyProc notify);
            
unsigned short * wallGetBackgroundGradientHighlightColor (CompDisplay *d);
unsigned short   wallGetBackgroundGradientHighlightColorRed (CompDisplay *d);
unsigned short   wallGetBackgroundGradientHighlightColorGreen (CompDisplay *d);
unsigned short   wallGetBackgroundGradientHighlightColorBlue (CompDisplay *d);
unsigned short   wallGetBackgroundGradientHighlightColorAlpha (CompDisplay *d);
CompOption *     wallGetBackgroundGradientHighlightColorOption (CompDisplay *d);
void             wallSetBackgroundGradientHighlightColorNotify (CompDisplay *d, wallDisplayOptionChangeNotifyProc notify);
            
unsigned short * wallGetBackgroundGradientShadowColor (CompDisplay *d);
unsigned short   wallGetBackgroundGradientShadowColorRed (CompDisplay *d);
unsigned short   wallGetBackgroundGradientShadowColorGreen (CompDisplay *d);
unsigned short   wallGetBackgroundGradientShadowColorBlue (CompDisplay *d);
unsigned short   wallGetBackgroundGradientShadowColorAlpha (CompDisplay *d);
CompOption *     wallGetBackgroundGradientShadowColorOption (CompDisplay *d);
void             wallSetBackgroundGradientShadowColorNotify (CompDisplay *d, wallDisplayOptionChangeNotifyProc notify);
            
unsigned short * wallGetThumbGradientBaseColor (CompDisplay *d);
unsigned short   wallGetThumbGradientBaseColorRed (CompDisplay *d);
unsigned short   wallGetThumbGradientBaseColorGreen (CompDisplay *d);
unsigned short   wallGetThumbGradientBaseColorBlue (CompDisplay *d);
unsigned short   wallGetThumbGradientBaseColorAlpha (CompDisplay *d);
CompOption *     wallGetThumbGradientBaseColorOption (CompDisplay *d);
void             wallSetThumbGradientBaseColorNotify (CompDisplay *d, wallDisplayOptionChangeNotifyProc notify);
            
unsigned short * wallGetThumbGradientHighlightColor (CompDisplay *d);
unsigned short   wallGetThumbGradientHighlightColorRed (CompDisplay *d);
unsigned short   wallGetThumbGradientHighlightColorGreen (CompDisplay *d);
unsigned short   wallGetThumbGradientHighlightColorBlue (CompDisplay *d);
unsigned short   wallGetThumbGradientHighlightColorAlpha (CompDisplay *d);
CompOption *     wallGetThumbGradientHighlightColorOption (CompDisplay *d);
void             wallSetThumbGradientHighlightColorNotify (CompDisplay *d, wallDisplayOptionChangeNotifyProc notify);
            
unsigned short * wallGetThumbHighlightGradientBaseColor (CompDisplay *d);
unsigned short   wallGetThumbHighlightGradientBaseColorRed (CompDisplay *d);
unsigned short   wallGetThumbHighlightGradientBaseColorGreen (CompDisplay *d);
unsigned short   wallGetThumbHighlightGradientBaseColorBlue (CompDisplay *d);
unsigned short   wallGetThumbHighlightGradientBaseColorAlpha (CompDisplay *d);
CompOption *     wallGetThumbHighlightGradientBaseColorOption (CompDisplay *d);
void             wallSetThumbHighlightGradientBaseColorNotify (CompDisplay *d, wallDisplayOptionChangeNotifyProc notify);
            
unsigned short * wallGetThumbHighlightGradientShadowColor (CompDisplay *d);
unsigned short   wallGetThumbHighlightGradientShadowColorRed (CompDisplay *d);
unsigned short   wallGetThumbHighlightGradientShadowColorGreen (CompDisplay *d);
unsigned short   wallGetThumbHighlightGradientShadowColorBlue (CompDisplay *d);
unsigned short   wallGetThumbHighlightGradientShadowColorAlpha (CompDisplay *d);
CompOption *     wallGetThumbHighlightGradientShadowColorOption (CompDisplay *d);
void             wallSetThumbHighlightGradientShadowColorNotify (CompDisplay *d, wallDisplayOptionChangeNotifyProc notify);
            
unsigned short * wallGetArrowBaseColor (CompDisplay *d);
unsigned short   wallGetArrowBaseColorRed (CompDisplay *d);
unsigned short   wallGetArrowBaseColorGreen (CompDisplay *d);
unsigned short   wallGetArrowBaseColorBlue (CompDisplay *d);
unsigned short   wallGetArrowBaseColorAlpha (CompDisplay *d);
CompOption *     wallGetArrowBaseColorOption (CompDisplay *d);
void             wallSetArrowBaseColorNotify (CompDisplay *d, wallDisplayOptionChangeNotifyProc notify);
            
unsigned short * wallGetArrowShadowColor (CompDisplay *d);
unsigned short   wallGetArrowShadowColorRed (CompDisplay *d);
unsigned short   wallGetArrowShadowColorGreen (CompDisplay *d);
unsigned short   wallGetArrowShadowColorBlue (CompDisplay *d);
unsigned short   wallGetArrowShadowColorAlpha (CompDisplay *d);
CompOption *     wallGetArrowShadowColorOption (CompDisplay *d);
void             wallSetArrowShadowColorNotify (CompDisplay *d, wallDisplayOptionChangeNotifyProc notify);
            
Bool             wallGetAllowWraparound (CompDisplay *d);
CompOption *     wallGetAllowWraparoundOption (CompDisplay *d);
void             wallSetAllowWraparoundNotify (CompDisplay *d, wallDisplayOptionChangeNotifyProc notify);
            
float            wallGetSlideDuration (CompDisplay *d);
CompOption *     wallGetSlideDurationOption (CompDisplay *d);
void             wallSetSlideDurationNotify (CompDisplay *d, wallDisplayOptionChangeNotifyProc notify);
            
CompAction *     wallGetLeft (CompDisplay *d);
void             wallSetLeftInitiate (CompDisplay *d, CompActionCallBackProc init);
void             wallSetLeftTerminate (CompDisplay *d, CompActionCallBackProc term);
CompOption *     wallGetLeftOption (CompDisplay *d);
void             wallSetLeftNotify (CompDisplay *d, wallDisplayOptionChangeNotifyProc notify);
            
CompAction *     wallGetRight (CompDisplay *d);
void             wallSetRightInitiate (CompDisplay *d, CompActionCallBackProc init);
void             wallSetRightTerminate (CompDisplay *d, CompActionCallBackProc term);
CompOption *     wallGetRightOption (CompDisplay *d);
void             wallSetRightNotify (CompDisplay *d, wallDisplayOptionChangeNotifyProc notify);
            
CompAction *     wallGetUp (CompDisplay *d);
void             wallSetUpInitiate (CompDisplay *d, CompActionCallBackProc init);
void             wallSetUpTerminate (CompDisplay *d, CompActionCallBackProc term);
CompOption *     wallGetUpOption (CompDisplay *d);
void             wallSetUpNotify (CompDisplay *d, wallDisplayOptionChangeNotifyProc notify);
            
CompAction *     wallGetDown (CompDisplay *d);
void             wallSetDownInitiate (CompDisplay *d, CompActionCallBackProc init);
void             wallSetDownTerminate (CompDisplay *d, CompActionCallBackProc term);
CompOption *     wallGetDownOption (CompDisplay *d);
void             wallSetDownNotify (CompDisplay *d, wallDisplayOptionChangeNotifyProc notify);
            
CompAction *     wallGetNext (CompDisplay *d);
void             wallSetNextInitiate (CompDisplay *d, CompActionCallBackProc init);
void             wallSetNextTerminate (CompDisplay *d, CompActionCallBackProc term);
CompOption *     wallGetNextOption (CompDisplay *d);
void             wallSetNextNotify (CompDisplay *d, wallDisplayOptionChangeNotifyProc notify);
            
CompAction *     wallGetPrev (CompDisplay *d);
void             wallSetPrevInitiate (CompDisplay *d, CompActionCallBackProc init);
void             wallSetPrevTerminate (CompDisplay *d, CompActionCallBackProc term);
CompOption *     wallGetPrevOption (CompDisplay *d);
void             wallSetPrevNotify (CompDisplay *d, wallDisplayOptionChangeNotifyProc notify);
            
CompAction *     wallGetLeftWindow (CompDisplay *d);
void             wallSetLeftWindowInitiate (CompDisplay *d, CompActionCallBackProc init);
void             wallSetLeftWindowTerminate (CompDisplay *d, CompActionCallBackProc term);
CompOption *     wallGetLeftWindowOption (CompDisplay *d);
void             wallSetLeftWindowNotify (CompDisplay *d, wallDisplayOptionChangeNotifyProc notify);
            
CompAction *     wallGetRightWindow (CompDisplay *d);
void             wallSetRightWindowInitiate (CompDisplay *d, CompActionCallBackProc init);
void             wallSetRightWindowTerminate (CompDisplay *d, CompActionCallBackProc term);
CompOption *     wallGetRightWindowOption (CompDisplay *d);
void             wallSetRightWindowNotify (CompDisplay *d, wallDisplayOptionChangeNotifyProc notify);
            
CompAction *     wallGetUpWindow (CompDisplay *d);
void             wallSetUpWindowInitiate (CompDisplay *d, CompActionCallBackProc init);
void             wallSetUpWindowTerminate (CompDisplay *d, CompActionCallBackProc term);
CompOption *     wallGetUpWindowOption (CompDisplay *d);
void             wallSetUpWindowNotify (CompDisplay *d, wallDisplayOptionChangeNotifyProc notify);
            
CompAction *     wallGetDownWindow (CompDisplay *d);
void             wallSetDownWindowInitiate (CompDisplay *d, CompActionCallBackProc init);
void             wallSetDownWindowTerminate (CompDisplay *d, CompActionCallBackProc term);
CompOption *     wallGetDownWindowOption (CompDisplay *d);
void             wallSetDownWindowNotify (CompDisplay *d, wallDisplayOptionChangeNotifyProc notify);
            
CompAction *     wallGetFlipLeft (CompDisplay *d);
void             wallSetFlipLeftInitiate (CompDisplay *d, CompActionCallBackProc init);
void             wallSetFlipLeftTerminate (CompDisplay *d, CompActionCallBackProc term);
CompOption *     wallGetFlipLeftOption (CompDisplay *d);
void             wallSetFlipLeftNotify (CompDisplay *d, wallDisplayOptionChangeNotifyProc notify);
            
CompAction *     wallGetFlipRight (CompDisplay *d);
void             wallSetFlipRightInitiate (CompDisplay *d, CompActionCallBackProc init);
void             wallSetFlipRightTerminate (CompDisplay *d, CompActionCallBackProc term);
CompOption *     wallGetFlipRightOption (CompDisplay *d);
void             wallSetFlipRightNotify (CompDisplay *d, wallDisplayOptionChangeNotifyProc notify);
            
CompAction *     wallGetFlipUp (CompDisplay *d);
void             wallSetFlipUpInitiate (CompDisplay *d, CompActionCallBackProc init);
void             wallSetFlipUpTerminate (CompDisplay *d, CompActionCallBackProc term);
CompOption *     wallGetFlipUpOption (CompDisplay *d);
void             wallSetFlipUpNotify (CompDisplay *d, wallDisplayOptionChangeNotifyProc notify);
            
CompAction *     wallGetFlipDown (CompDisplay *d);
void             wallSetFlipDownInitiate (CompDisplay *d, CompActionCallBackProc init);
void             wallSetFlipDownTerminate (CompDisplay *d, CompActionCallBackProc term);
CompOption *     wallGetFlipDownOption (CompDisplay *d);
void             wallSetFlipDownNotify (CompDisplay *d, wallDisplayOptionChangeNotifyProc notify);
            
int              wallGetMmmode (CompScreen *s);
CompOption *     wallGetMmmodeOption (CompScreen *s);
void             wallSetMmmodeNotify (CompScreen *s, wallScreenOptionChangeNotifyProc notify);
            
Bool             wallGetEdgeflipPointer (CompScreen *s);
CompOption *     wallGetEdgeflipPointerOption (CompScreen *s);
void             wallSetEdgeflipPointerNotify (CompScreen *s, wallScreenOptionChangeNotifyProc notify);
            
Bool             wallGetEdgeflipMove (CompScreen *s);
CompOption *     wallGetEdgeflipMoveOption (CompScreen *s);
void             wallSetEdgeflipMoveNotify (CompScreen *s, wallScreenOptionChangeNotifyProc notify);
            
Bool             wallGetEdgeflipDnd (CompScreen *s);
CompOption *     wallGetEdgeflipDndOption (CompScreen *s);
void             wallSetEdgeflipDndNotify (CompScreen *s, wallScreenOptionChangeNotifyProc notify);
            
#ifdef  __cplusplus
}
#endif

#endif
