/*
 * This file is autogenerated with bcop:
 * The Ecomp option code generator
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 */

#ifndef _SCALEFILTER_OPTIONS_H
#define _SCALEFILTER_OPTIONS_H

#ifndef _SCALEFILTER_OPTIONS_INTERNAL
#define getCompPluginInfo scalefilterOptionsGetCompPluginInfo
#endif

#ifdef  __cplusplus
extern "C" {
#endif

CompPluginVTable *scalefilterOptionsGetCompPluginInfo (void);

typedef enum
{
    ScalefilterDisplayOptionNum
} ScalefilterDisplayOptions;

typedef void (*scalefilterDisplayOptionChangeNotifyProc) (CompDisplay *display, CompOption *opt, ScalefilterDisplayOptions num);

CompOption *scalefilterGetDisplayOption (CompDisplay *d, ScalefilterDisplayOptions num);

typedef enum
{
    ScalefilterScreenOptionTimeout,
    ScalefilterScreenOptionFilterCaseInsensitive,
    ScalefilterScreenOptionFilterDisplay,
    ScalefilterScreenOptionFontBold,
    ScalefilterScreenOptionFontSize,
    ScalefilterScreenOptionBorderSize,
    ScalefilterScreenOptionFontColor,
    ScalefilterScreenOptionBackColor,
    ScalefilterScreenOptionNum
} ScalefilterScreenOptions;

typedef void (*scalefilterScreenOptionChangeNotifyProc) (CompScreen *screen, CompOption *opt, ScalefilterScreenOptions num);

CompOption *scalefilterGetScreenOption (CompScreen *s, ScalefilterScreenOptions num);

int              scalefilterGetTimeout (CompScreen *s);
CompOption *     scalefilterGetTimeoutOption (CompScreen *s);
void             scalefilterSetTimeoutNotify (CompScreen *s, scalefilterScreenOptionChangeNotifyProc notify);
            
Bool             scalefilterGetFilterCaseInsensitive (CompScreen *s);
CompOption *     scalefilterGetFilterCaseInsensitiveOption (CompScreen *s);
void             scalefilterSetFilterCaseInsensitiveNotify (CompScreen *s, scalefilterScreenOptionChangeNotifyProc notify);
            
Bool             scalefilterGetFilterDisplay (CompScreen *s);
CompOption *     scalefilterGetFilterDisplayOption (CompScreen *s);
void             scalefilterSetFilterDisplayNotify (CompScreen *s, scalefilterScreenOptionChangeNotifyProc notify);
            
Bool             scalefilterGetFontBold (CompScreen *s);
CompOption *     scalefilterGetFontBoldOption (CompScreen *s);
void             scalefilterSetFontBoldNotify (CompScreen *s, scalefilterScreenOptionChangeNotifyProc notify);
            
int              scalefilterGetFontSize (CompScreen *s);
CompOption *     scalefilterGetFontSizeOption (CompScreen *s);
void             scalefilterSetFontSizeNotify (CompScreen *s, scalefilterScreenOptionChangeNotifyProc notify);
            
int              scalefilterGetBorderSize (CompScreen *s);
CompOption *     scalefilterGetBorderSizeOption (CompScreen *s);
void             scalefilterSetBorderSizeNotify (CompScreen *s, scalefilterScreenOptionChangeNotifyProc notify);
            
unsigned short * scalefilterGetFontColor (CompScreen *s);
unsigned short   scalefilterGetFontColorRed (CompScreen *s);
unsigned short   scalefilterGetFontColorGreen (CompScreen *s);
unsigned short   scalefilterGetFontColorBlue (CompScreen *s);
unsigned short   scalefilterGetFontColorAlpha (CompScreen *s);
CompOption *     scalefilterGetFontColorOption (CompScreen *s);
void             scalefilterSetFontColorNotify (CompScreen *s, scalefilterScreenOptionChangeNotifyProc notify);
            
unsigned short * scalefilterGetBackColor (CompScreen *s);
unsigned short   scalefilterGetBackColorRed (CompScreen *s);
unsigned short   scalefilterGetBackColorGreen (CompScreen *s);
unsigned short   scalefilterGetBackColorBlue (CompScreen *s);
unsigned short   scalefilterGetBackColorAlpha (CompScreen *s);
CompOption *     scalefilterGetBackColorOption (CompScreen *s);
void             scalefilterSetBackColorNotify (CompScreen *s, scalefilterScreenOptionChangeNotifyProc notify);
            
#ifdef  __cplusplus
}
#endif

#endif
